name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create coding style directory
        run: mkdir check_codingstyle
      - name: Download script
        run: wget --no-check-certificate -O check_codingstyle/coding-style.sh https://uploads.admlbs.fr/coding-style.sh
      - name: Set permissions
        run: chmod 0777 check_codingstyle/coding-style.sh
      - name: Run coding style checker
        run: ./check_codingstyle/coding-style.sh .. .
  check_major:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
        - name: Check number of "MAJOR:" occurrences
          run: |
            major_occurrences=$(grep -c "MAJOR:" coding-style-reports.log)
            if [ "$major_occurrences" -gt 9 ]; then
                echo "Too many MAJOR occurrences ($major_occurrences - 9)!"
                grep "MAJOR:" coding-style-reports.log | tail -n +10
                exit 1
            fi
  check_minor:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
        - name: Check number of "MINOR:" occurrences
          run: |
            minor_occurrences=$(grep -c "MINOR:" coding-style-reports.log)
            if [ "$minor_occurrences" -gt 5 ]; then
              echo "Too many MINOR occurrences ($minor_occurrences - 5)!"
              grep "MINOR:" coding-style-reports.log | tail -n +6
              exit 1
            fi
  check_compilation:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
        - name: Install UUID
          run: sudo apt-get update && sudo apt-get -y install uuid-dev
        - name: Run make
          run: make
